### ISSUE TITLE
Meeting - 30.05.2023

### ISSUE THREAD

**Issue by dimitrod** [MikaMk4/Gruppe5#42]
## Teilnehmer:

 - @MikaMk4 
 - @dimitrod 
 - @F1nnian 
 - @lenseB 

## Thema - Feedback/Konsultation 3. mit Stefan Reschke:

 - Beim Speichern - redundanz gönnen, muss nicht optimiert sein (ggf. später).
 - Usecases ableitbar von der Feature Liste
 - Usecases als Tests in einem Ordner application.usecases ablegen (??)
 - Bei anderen Gruppen CLI Adapter abschauen

## To-Do's:
 
- [ ] Features kürzen/verbinden
- [x] Trainer in Training-Session oder Learning-Session umbenennen (Lesbarkeit?)
- [x] buildTrainer als Factory-Method-Pattern (createTrainer) auslagern
- [ ] Trainer komplett abspeichern in saveTrainingInstace (statt die Collection der Boxen)
- [x] NullPointerException nicht catchen, sondern vorher testen ob null (->persisteneLoadPort)
- [x] buildFromBoxes zu createFromBoxes ändern (wieder Factory-Method-Pattern statt Builder)
- [x] Bei anderen Gruppen CLI Adapter abschauen
